project:
  type: website
  output-dir: docs

website:
  title: "plantillas_personalizadas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - midnight
      - brand
    css: styles.css
    toc: true

editor: visual

